
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/royce/.local/lib/python3.10/site-packages/cmake/data/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (PROJECT)"
    message: |
      The system is: Linux - 6.8.0-100-generic - x86_64
...
