#define TORCH_ASSERT_ONLY_METHOD_OPERATORS
// @generated by torchgen/gen.py from ViewMetaClasses.h

#include <ATen/FunctionalStorageImpl.h>

namespace at {
namespace functionalization {


struct TORCH_API _fw_primal_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_fw_primal_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* level */);

  _fw_primal_ViewMeta(const SerializableTuple& tpl)
      : _fw_primal_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  _fw_primal_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t level)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        level(level) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, level);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t level;
};

struct TORCH_API _make_dual_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_make_dual_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      const at::Tensor & /* tangent */,
      int64_t /* level */);

  _make_dual_ViewMeta(const SerializableTuple& tpl)
      : _make_dual_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  _make_dual_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, const at::Tensor & tangent, int64_t level)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        tangent(tangent),
        level(level) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, tangent, level);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  const at::Tensor & tangent;
  int64_t level;
};

struct TORCH_API view_as_real_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(view_as_real_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  view_as_real_ViewMeta(const SerializableTuple& tpl)
      : view_as_real_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  view_as_real_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API view_as_complex_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(view_as_complex_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  view_as_complex_ViewMeta(const SerializableTuple& tpl)
      : view_as_complex_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  view_as_complex_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API _conj_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_conj_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _conj_ViewMeta(const SerializableTuple& tpl)
      : _conj_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _conj_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API _neg_view_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_neg_view_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _neg_view_ViewMeta(const SerializableTuple& tpl)
      : _neg_view_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _neg_view_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API as_strided_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(as_strided_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* size */,
      ::std::vector<c10::SymInt> /* stride */,
      ::std::optional<c10::SymInt> /* storage_offset */);

  as_strided_ViewMeta(const SerializableTuple& tpl)
      : as_strided_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  as_strided_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef size, c10::SymIntArrayRef stride, ::std::optional<c10::SymInt> storage_offset)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/true, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()),
        stride(stride.vec()),
        storage_offset(storage_offset) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size, stride, storage_offset);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> size;
  ::std::vector<c10::SymInt> stride;
  ::std::optional<c10::SymInt> storage_offset;
};

struct TORCH_API as_strided__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(as_strided__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* size */,
      ::std::vector<c10::SymInt> /* stride */,
      ::std::optional<c10::SymInt> /* storage_offset */);

  as_strided__ViewMeta(const SerializableTuple& tpl)
      : as_strided__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  as_strided__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef size, c10::SymIntArrayRef stride, ::std::optional<c10::SymInt> storage_offset)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()),
        stride(stride.vec()),
        storage_offset(storage_offset) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size, stride, storage_offset);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> size;
  ::std::vector<c10::SymInt> stride;
  ::std::optional<c10::SymInt> storage_offset;
};

struct TORCH_API _sparse_broadcast_to_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_sparse_broadcast_to_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<int64_t> /* size */);

  _sparse_broadcast_to_ViewMeta(const SerializableTuple& tpl)
      : _sparse_broadcast_to_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  _sparse_broadcast_to_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, at::IntArrayRef size)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<int64_t> size;
};

struct TORCH_API diagonal_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(diagonal_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* offset */,
      int64_t /* dim1 */,
      int64_t /* dim2 */);

  diagonal_ViewMeta(const SerializableTuple& tpl)
      : diagonal_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  diagonal_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t offset, int64_t dim1, int64_t dim2)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        offset(offset),
        dim1(dim1),
        dim2(dim2) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, offset, dim1, dim2);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t offset;
  int64_t dim1;
  int64_t dim2;
};

struct TORCH_API expand_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(expand_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* size */,
      bool /* implicit */);

  expand_ViewMeta(const SerializableTuple& tpl)
      : expand_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  expand_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef size, bool implicit)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()),
        implicit(implicit) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size, implicit);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> size;
  bool implicit;
};

struct TORCH_API permute_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(permute_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<int64_t> /* dims */);

  permute_ViewMeta(const SerializableTuple& tpl)
      : permute_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  permute_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, at::IntArrayRef dims)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dims(dims.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dims);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<int64_t> dims;
};

struct TORCH_API _reshape_alias_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_reshape_alias_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* size */,
      ::std::vector<c10::SymInt> /* stride */);

  _reshape_alias_ViewMeta(const SerializableTuple& tpl)
      : _reshape_alias_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  _reshape_alias_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef size, c10::SymIntArrayRef stride)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()),
        stride(stride.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size, stride);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> size;
  ::std::vector<c10::SymInt> stride;
};

struct TORCH_API select_int_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(select_int_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */,
      c10::SymInt /* index */);

  select_int_ViewMeta(const SerializableTuple& tpl)
      : select_int_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  select_int_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim, c10::SymInt index)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim),
        index(index) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim, index);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
  c10::SymInt index;
};

struct TORCH_API detach_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(detach_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  detach_ViewMeta(const SerializableTuple& tpl)
      : detach_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  detach_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API detach__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(detach__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  detach__ViewMeta(const SerializableTuple& tpl)
      : detach__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  detach__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API slice_Tensor_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(slice_Tensor_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */,
      ::std::optional<c10::SymInt> /* start */,
      ::std::optional<c10::SymInt> /* end */,
      c10::SymInt /* step */);

  slice_Tensor_ViewMeta(const SerializableTuple& tpl)
      : slice_Tensor_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl), std::get<6>(tpl)) {}

  slice_Tensor_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim, ::std::optional<c10::SymInt> start, ::std::optional<c10::SymInt> end, c10::SymInt step)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim),
        start(start),
        end(end),
        step(step) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim, start, end, step);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
  ::std::optional<c10::SymInt> start;
  ::std::optional<c10::SymInt> end;
  c10::SymInt step;
};

struct TORCH_API slice_inverse_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(slice_inverse_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      const at::Tensor & /* src */,
      int64_t /* dim */,
      ::std::optional<c10::SymInt> /* start */,
      ::std::optional<c10::SymInt> /* end */,
      c10::SymInt /* step */);

  slice_inverse_ViewMeta(const SerializableTuple& tpl)
      : slice_inverse_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl), std::get<6>(tpl), std::get<7>(tpl)) {}

  slice_inverse_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, const at::Tensor & src, int64_t dim, ::std::optional<c10::SymInt> start, ::std::optional<c10::SymInt> end, c10::SymInt step)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        src(src),
        dim(dim),
        start(start),
        end(end),
        step(step) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, src, dim, start, end, step);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  const at::Tensor & src;
  int64_t dim;
  ::std::optional<c10::SymInt> start;
  ::std::optional<c10::SymInt> end;
  c10::SymInt step;
};

struct TORCH_API split_Tensor_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(split_Tensor_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      int64_t /* out_index */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      c10::SymInt /* split_size */,
      int64_t /* dim */);

  split_Tensor_ViewMeta(const SerializableTuple& tpl)
      : split_Tensor_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  split_Tensor_ViewMeta(bool has_symbolic_inputs, int64_t out_index, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymInt split_size, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/true, /*is_as_strided=*/false, /*out_index=*/out_index),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        split_size(split_size),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;
  std::shared_ptr<ViewMeta> to_out_index(int64_t out_idx) override;

  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, split_size, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  c10::SymInt split_size;
  int64_t dim;
};

struct TORCH_API split_with_sizes_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(split_with_sizes_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      int64_t /* out_index */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* split_sizes */,
      int64_t /* dim */);

  split_with_sizes_ViewMeta(const SerializableTuple& tpl)
      : split_with_sizes_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  split_with_sizes_ViewMeta(bool has_symbolic_inputs, int64_t out_index, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef split_sizes, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/true, /*is_as_strided=*/false, /*out_index=*/out_index),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        split_sizes(split_sizes.vec()),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;
  std::shared_ptr<ViewMeta> to_out_index(int64_t out_idx) override;

  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, split_sizes, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> split_sizes;
  int64_t dim;
};

struct TORCH_API squeeze_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  squeeze_ViewMeta(const SerializableTuple& tpl)
      : squeeze_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  squeeze_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API squeeze__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  squeeze__ViewMeta(const SerializableTuple& tpl)
      : squeeze__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  squeeze__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API squeeze_dim_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze_dim_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */);

  squeeze_dim_ViewMeta(const SerializableTuple& tpl)
      : squeeze_dim_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  squeeze_dim_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
};

struct TORCH_API squeeze__dim_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze__dim_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */);

  squeeze__dim_ViewMeta(const SerializableTuple& tpl)
      : squeeze__dim_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  squeeze__dim_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
};

struct TORCH_API squeeze_dims_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze_dims_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<int64_t> /* dim */);

  squeeze_dims_ViewMeta(const SerializableTuple& tpl)
      : squeeze_dims_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  squeeze_dims_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, at::IntArrayRef dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<int64_t> dim;
};

struct TORCH_API squeeze__dims_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(squeeze__dims_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<int64_t> /* dim */);

  squeeze__dims_ViewMeta(const SerializableTuple& tpl)
      : squeeze__dims_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  squeeze__dims_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, at::IntArrayRef dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<int64_t> dim;
};

struct TORCH_API t_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(t_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  t_ViewMeta(const SerializableTuple& tpl)
      : t_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  t_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API t__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(t__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  t__ViewMeta(const SerializableTuple& tpl)
      : t__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  t__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API transpose_int_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(transpose_int_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim0 */,
      int64_t /* dim1 */);

  transpose_int_ViewMeta(const SerializableTuple& tpl)
      : transpose_int_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  transpose_int_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim0, int64_t dim1)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim0(dim0),
        dim1(dim1) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim0, dim1);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim0;
  int64_t dim1;
};

struct TORCH_API transpose__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(transpose__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim0 */,
      int64_t /* dim1 */);

  transpose__ViewMeta(const SerializableTuple& tpl)
      : transpose__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  transpose__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim0, int64_t dim1)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim0(dim0),
        dim1(dim1) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim0, dim1);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim0;
  int64_t dim1;
};

struct TORCH_API _nested_view_from_buffer_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_nested_view_from_buffer_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      const at::Tensor & /* nested_size */,
      const at::Tensor & /* nested_strides */,
      const at::Tensor & /* offsets */);

  _nested_view_from_buffer_ViewMeta(const SerializableTuple& tpl)
      : _nested_view_from_buffer_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  _nested_view_from_buffer_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, const at::Tensor & nested_size, const at::Tensor & nested_strides, const at::Tensor & offsets)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        nested_size(nested_size),
        nested_strides(nested_strides),
        offsets(offsets) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, nested_size, nested_strides, offsets);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  const at::Tensor & nested_size;
  const at::Tensor & nested_strides;
  const at::Tensor & offsets;
};

struct TORCH_API _nested_view_from_jagged_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_nested_view_from_jagged_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      const at::Tensor & /* offsets */,
      const at::Tensor & /* dummy */,
      const ::std::optional<at::Tensor> & /* lengths */,
      int64_t /* ragged_idx */,
      const ::std::optional<at::Tensor> & /* min_seqlen */,
      const ::std::optional<at::Tensor> & /* max_seqlen */);

  _nested_view_from_jagged_ViewMeta(const SerializableTuple& tpl)
      : _nested_view_from_jagged_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl), std::get<6>(tpl), std::get<7>(tpl), std::get<8>(tpl)) {}

  _nested_view_from_jagged_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, const at::Tensor & offsets, const at::Tensor & dummy, const ::std::optional<at::Tensor> & lengths, int64_t ragged_idx, const ::std::optional<at::Tensor> & min_seqlen, const ::std::optional<at::Tensor> & max_seqlen)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        offsets(offsets),
        dummy(dummy),
        lengths(lengths),
        ragged_idx(ragged_idx),
        min_seqlen(min_seqlen),
        max_seqlen(max_seqlen) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, offsets, dummy, lengths, ragged_idx, min_seqlen, max_seqlen);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  const at::Tensor & offsets;
  const at::Tensor & dummy;
  const ::std::optional<at::Tensor> & lengths;
  int64_t ragged_idx;
  const ::std::optional<at::Tensor> & min_seqlen;
  const ::std::optional<at::Tensor> & max_seqlen;
};

struct TORCH_API _nested_get_values_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_nested_get_values_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _nested_get_values_ViewMeta(const SerializableTuple& tpl)
      : _nested_get_values_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _nested_get_values_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API unsqueeze_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(unsqueeze_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */);

  unsqueeze_ViewMeta(const SerializableTuple& tpl)
      : unsqueeze_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  unsqueeze_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
};

struct TORCH_API unsqueeze__ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(unsqueeze__ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */);

  unsqueeze__ViewMeta(const SerializableTuple& tpl)
      : unsqueeze__ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  unsqueeze__ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
};

struct TORCH_API _indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _indices_ViewMeta(const SerializableTuple& tpl)
      : _indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API _values_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_values_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _values_ViewMeta(const SerializableTuple& tpl)
      : _values_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _values_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  indices_ViewMeta(const SerializableTuple& tpl)
      : indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API values_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(values_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  values_ViewMeta(const SerializableTuple& tpl)
      : values_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  values_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API crow_indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(crow_indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  crow_indices_ViewMeta(const SerializableTuple& tpl)
      : crow_indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  crow_indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API col_indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(col_indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  col_indices_ViewMeta(const SerializableTuple& tpl)
      : col_indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  col_indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API ccol_indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(ccol_indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  ccol_indices_ViewMeta(const SerializableTuple& tpl)
      : ccol_indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  ccol_indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API row_indices_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(row_indices_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  row_indices_ViewMeta(const SerializableTuple& tpl)
      : row_indices_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  row_indices_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API unbind_int_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(unbind_int_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      int64_t /* out_index */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dim */);

  unbind_int_ViewMeta(const SerializableTuple& tpl)
      : unbind_int_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl)) {}

  unbind_int_ViewMeta(bool has_symbolic_inputs, int64_t out_index, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dim)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/true, /*is_as_strided=*/false, /*out_index=*/out_index),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dim(dim) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;
  std::shared_ptr<ViewMeta> to_out_index(int64_t out_idx) override;

  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, out_index, reapply_views, inverse_return_mode, dim);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dim;
};

struct TORCH_API lift_fresh_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(lift_fresh_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  lift_fresh_ViewMeta(const SerializableTuple& tpl)
      : lift_fresh_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  lift_fresh_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API view_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(view_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      ::std::vector<c10::SymInt> /* size */);

  view_ViewMeta(const SerializableTuple& tpl)
      : view_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  view_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, c10::SymIntArrayRef size)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        size(size.vec()) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, size);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  ::std::vector<c10::SymInt> size;
};

struct TORCH_API view_dtype_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(view_dtype_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      at::ScalarType /* dtype */);

  view_dtype_ViewMeta(const SerializableTuple& tpl)
      : view_dtype_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl)) {}

  view_dtype_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, at::ScalarType dtype)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dtype(dtype) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dtype);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  at::ScalarType dtype;
};

struct TORCH_API unfold_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(unfold_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */,
      int64_t /* dimension */,
      int64_t /* size */,
      int64_t /* step */);

  unfold_ViewMeta(const SerializableTuple& tpl)
      : unfold_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl), std::get<3>(tpl), std::get<4>(tpl), std::get<5>(tpl)) {}

  unfold_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode, int64_t dimension, int64_t size, int64_t step)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode),
        dimension(dimension),
        size(size),
        step(step) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode, dimension, size, step);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
  int64_t dimension;
  int64_t size;
  int64_t step;
};

struct TORCH_API alias_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(alias_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  alias_ViewMeta(const SerializableTuple& tpl)
      : alias_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  alias_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

struct TORCH_API _test_autograd_multiple_dispatch_view_ViewMeta : public ViewMeta {
  FUNCTIONALIZATION_VIEWMETA_NAME(_test_autograd_multiple_dispatch_view_ViewMeta)
  FUNCTIONALIZATION_VIEWMETA_SERIALIZABLE_TUPLE(
      bool /* has_symbolic_inputs */,
      bool /* reapply_views */,
      at::functionalization::InverseReturnMode /* inverse_return_mode */);

  _test_autograd_multiple_dispatch_view_ViewMeta(const SerializableTuple& tpl)
      : _test_autograd_multiple_dispatch_view_ViewMeta(std::get<0>(tpl), std::get<1>(tpl), std::get<2>(tpl)) {}

  _test_autograd_multiple_dispatch_view_ViewMeta(bool has_symbolic_inputs, bool reapply_views, at::functionalization::InverseReturnMode inverse_return_mode)
      : at::functionalization::ViewMeta(has_symbolic_inputs, /*is_multi_output=*/false, /*is_as_strided=*/false, /*out_index=*/0),
        reapply_views(reapply_views),
        inverse_return_mode(inverse_return_mode) {}

  Tensor forward(const Tensor& base) override;
  Tensor reverse(const Tensor& base, const Tensor& mutated_view) override;


  SerializableTuple to_serializable_tuple() {
    return std::make_tuple(has_symbolic_inputs, reapply_views, inverse_return_mode);
  }

  bool reapply_views;
  at::functionalization::InverseReturnMode inverse_return_mode;
};

} // namespace functionalization
} // namespace at
